
.PHONY: clean
clean:
	rm -rf ./i/*.png
	rm -rf ./ii/*.png
	rm -rf ./iii/*.png
	rm -rf ./iv/*.png
	rm -rf ./v/*.png
	rm -rf ./vi/*.png
	rm -rf ./vii/*.png
	rm -rf ./viii/*.png
	rm -rf ./ix/*.png
	rm -rf ./x/*.png
